<a href="https://colab.research.google.com/github/shuklasid19/tensorflow-2.0/blob/main/tensorflowbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf

In [7]:
#define a tensorflow constant matrix
tensor = tf.constant([[23, 4], [32, 51]])

In [8]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]], dtype=int32)>

In [9]:
variable = tf.Variable([[30, 20], [10, 45]])

In [10]:
variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[30, 20],
       [10, 45]], dtype=int32)>

In [11]:
variable.get_shape()

TensorShape([2, 2])

In [12]:
variable+2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[32, 22],
       [12, 47]], dtype=int32)>

In [14]:
tensor20 = tf.constant([[34, 45], [56,32]])

In [15]:
tensor20

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 45],
       [56, 32]], dtype=int32)>

In [16]:
tensor20.shape

TensorShape([2, 2])

In [17]:
tensor20.numpy()

array([[34, 45],
       [56, 32]], dtype=int32)

In [20]:
import numpy as np
numpytensor = np.array([[23, 4], [32, 51]])

In [22]:
tensorffromnumpy  = tf.constant(numpytensor)

In [24]:
tensor = tf.constant([[1, 2], [3 , 4]])
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [25]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [26]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [27]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [29]:
np.dot(tensor, tensor20)

array([[146, 109],
       [326, 263]], dtype=int32)

In [30]:
tf2_var = tf.Variable([[1., 2. ,3. ], [4. ,5. ,6. ]])
tf2_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [31]:
tf2_var.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [32]:
tf2_var[0, 2].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [33]:
tf2_var

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 100.],
       [  4.,   5.,   6.]], dtype=float32)>

In [38]:
import tensorflow as tf

In [39]:
tf_string = tf.constant("tensorflow")
tf_string

<tf.Tensor: shape=(), dtype=string, numpy=b'tensorflow'>

In [42]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [43]:
tf.strings.unicode_decode(tf_string , "UTF8")

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([116, 101, 110, 115, 111, 114, 102, 108, 111, 119], dtype=int32)>

In [44]:
tf_array_str = tf.constant(["tensforlow", "deeplearni", "ai"])

In [45]:
for i in tf_array_str:
  print(i)

tf.Tensor(b'tensforlow', shape=(), dtype=string)
tf.Tensor(b'deeplearni', shape=(), dtype=string)
tf.Tensor(b'ai', shape=(), dtype=string)


In [46]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.


In [47]:
with tf.device("/cpu:0"):
    tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [48]:
tf_string_array.device

'/job:localhost/replica:0/task:0/device:CPU:0'